name: 'Add User to Org Action'
description: 'This action add the user that generated the event as member of the current organization'
runs:
  using: 'node16'
  main: 'index.js'
inputs:
  github_token:
    description: The GitHub token that can be used to obtain the Issue via API lookup
    default: ${{ github.token }}
    required: true
  github_user:
    description: The user that will be added to the organization
    default: ${{ github.actor }}
    required: true
  github_organization:
    description: The organization where the user will be added as member
    default: ${{ github.repository_owner }}
    required: true
